### ISSUE TITLE
[New] Project Proposal

### ISSUE THREAD

**Issue by ghulamghousdev** [Hire-o-Bot/Documentation#1]
We need to write a project proposal that has different sections and sub-sections. Each group member has been assigned one sub-section from each section. Following are the details: 

@ghulamghousdev need to research and pen down the following sub-sections:

- [x] 1.4 Our contribution
- [x] 5 System Requirements
- [x] 6.4 Time Feasibility
- [x] 7.1 Challenges 
- [x] 3.2 Applications

@ahmadbilaldev need to research and pen down the following sub-sections:

- [x] 1.1 Problem Statement and Motivation
- [x] 2.3 Academic Objectives
- [x] 4.1 Target Audience Group 1
- [x] 6.1 Technical Feasibility

@beingfaisal need to research and pen down the following sub-sections:

- [x] 1.2 Overview of the project
- [x] 2.1 Industry objectives
- [x] 3.1 Scope
- [x] 6.3 Economical feasibility
- [x] 7.2 Limitations

@ahmadzaheer-dev need to research and pen down the following sub-sections:

- [x] 1.3 Prior Work 
- [x] 2.2 Research Objectives
- [x] 6.1 Technical feasibility

**Comment by ahmadbilaldev** [comment]
- [x]  1.1 Problem Statement and Motivation
- [x]  2.3 Academic Objectives
- [x]  4.1 Target Audience Group 1
- [x]  6.1 Technical Feasibility
